services:
  jupyterhub:
    build: ./jupyterhub
    container_name: ${HUB_CONNECT_IP}
    ports: 
      - "8000:8000"
    volumes:
      # pass docker.sock for docker spawner
      - "/var/run/docker.sock:/var/run/docker.sock"
      # pass host system users to docker
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /etc/shadow:/etc/shadow:ro
    networks:
      - ${NETWORK_NAME}
    environment:
      - DATA_DIRECTORY=${DATA_DIRECTORY}
      - NETWORK_NAME=${NETWORK_NAME}
      - HUB_CONNECT_IP=${HUB_CONNECT_IP}
    expose:
      - 8000


networks:
  jupyterhub:
    driver: bridge
    name: ${NETWORK_NAME}
