name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-tensorflow-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build tensorflow-jupyterhub image
      run: docker build -t tensorflow-jupyterhub ./tensorflow-jupyterhub

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run docker compose build
      run: docker compose build

  test-selenium:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install requirepemts with pip
      run: pip install selenium pytest pytest-html pytest-selenium
    - name: pull scipy image
      run: docker pull jupyter/scipy-notebook:latest
    - name: start server
      run: docker compose -f docker-compose.yml -f test-compose.yml up -d
    - name: sleep so compose has some time to start the server
      run: sleep 10
    # todo: actually run the selenium tests
    - name: shut server down cleanly
      run: docker compose down
      
