name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-tensorflow-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build tensorflow-jupyterhub image
      run: docker build -t tensorflow-jupyterhub ./tensorflow-jupyterhub

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run docker compose build
      run: docker compose build

  test-selenium:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run selenium tests
    - run: pip install selenium pytest pytest-html pytest-selenium
    - run: docker pull jupyter/scipy-notebook:latest
    - run: docker compose up -d
    # sleep so compose has some time to start the server
    - run: sleep 10#
    # todo: actually run the selenium tests
    - run: docker compose down
      
